Fix regressions in zfstest-report.py script
This is a simple patch to fix a couple recent regressions to the
zfstest-report.py script, specifically:

    * The "inheritance/inherit_001_pos" was listed twice in the list of
      known failures, so the duplicate entry was removed.

    * The "redundancy" tests listed in the known list didn't properly
      quote the "FAIL" part of the entry, this would result in the
      script throwing an error when run. This patch adds those needed
      quotations.

Here's an example of the failure due to the missing quotations:

    running: /usr/bin/python /usr/local/zfstest-report.py results.txt
    Traceback (most recent call last):
      File "/usr/local/zfstest-report.py", line 49, in <module>
        'redundancy/redundancy_001_pos': FAIL,
    NameError: name 'FAIL' is not defined